### ISSUE TITLE
Question about the used Pre-trained Word Vector 

### ISSUE THREAD

**Issue by aishabadi** [SlothfulZhu/Wrongdoing-Monitor#1]
In the **1_darknetprocess** script's **pro_sumweight** method, you use **crawl-300d-2M-10.vec** as the pre-trained word vector. Is this the same pre-trained word vector provided by [Fast Text](https://fasttext.cc/docs/en/english-vectors.html) or a modified version? Thank you.

**Comment by SlothfulZhu** [comment]
In this work, we use the word vectors in the file (crawl-300d-2M.vec) provided by [Fast Text](https://fasttext.cc/docs/en/english-vectors.html). 
We only sampled some commonly used word vectors of numbers and letters to form our file, because most word vectors are unnecessary in our work and cannot be mapped one by one.  In particular, for complex strings, we use the sum of their corresponding vectors for each character as the word vector of the string. 

In your work, you can use the original file provided by [Fast Text](https://fasttext.cc/docs/en/english-vectors.html), or explore other better ways to obtain the more semantic word vectors
